/**:
  converter_costmap:
    converter_costmap:
      ros__parameters:
        always_send_full_costmap: True
        robot_base_frame: "robot/base_link"
        global_frame: "map"
        height: 5
        width: 5
        robot_radius: 0.22
        rolling_window: true
        plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          cost_scaling_factor: 3.0
          inflation_radius: 0.55
        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
          enabled: True
          scan:
            topic: /robot/laser/out
            max_obstacle_height: 2.0
            clearing: True
            marking: True
            raytrace_max_range: 3.0
            raytrace_min_range: 0.0
            obstacle_max_range: 2.5
            obstacle_min_range: 0.0
        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          enabled: True
          map_subscribe_transient_local: True